import React, { useEffect, useState } from 'react'; import { Alert, Button, Card, Col, Form, Input, InputNumber, Modal, Popconfirm, Row, Select, Space, Statistic, Table, Tabs, Tag, Typography, message } from 'antd'; import type { AdminDashboard, User, UserRole } from '@exam-maker/shared'; import { createAdminUser, createAiCostConfig, getAdminDashboard, listAdminAuditLogs, listAdminUsers, listAiCostConfigs, updateAdminUser } from '../services/admin';
const { Title, Text } = Typography; function errorText(error: unknown) { return (error as { response?: { data?: { error?: string } } })?.response?.data?.error ?? '操作失败'; }
const AdminConsole: React.FC = () => { const [dashboard, setDashboard] = useState<AdminDashboard | null>(null); const [users, setUsers] = useState<User[]>([]); const [audit, setAudit] = useState<Array<Record<string, unknown>>>([]); const [costs, setCosts] = useState<Array<Record<string, unknown>>>([]); const [userOpen, setUserOpen] = useState(false); const [costOpen, setCostOpen] = useState(false); const [userForm] = Form.useForm(); const [costForm] = Form.useForm();
  const load = () => Promise.all([getAdminDashboard(), listAdminUsers(), listAdminAuditLogs(), listAiCostConfigs()]).then(([d, u, a, c]) => { setDashboard(d); setUsers(u); setAudit(a); setCosts(c); }).catch(error => message.error(errorText(error))); useEffect(() => { load(); }, []);
  const createUser = async (values: { username: string; email: string; password: string; role: UserRole }) => { try { await createAdminUser(values); setUserOpen(false); userForm.resetFields(); await load(); } catch (error) { message.error(errorText(error)); } };
  const createCost = async (values: Record<string, unknown>) => { try { await createAiCostConfig({ ...values, effectiveFrom: new Date(String(values.effectiveFrom)).toISOString(), currency: 'USD' }); setCostOpen(false); costForm.resetFields(); await load(); } catch (error) { message.error(errorText(error)); } };
  const change = async (user: User, input: { isActive?: boolean; resetLoginState?: boolean }) => { try { await updateAdminUser(user.id, input); await load(); } catch (error) { message.error(errorText(error)); } };
  if (!dashboard) return <div>加载中...</div>; const ai = dashboard.ai;
  const overview = <><Alert type={dashboard.health.status === 'ok' ? 'success' : 'warning'} showIcon message={`系统状态：${dashboard.health.status}`} description={`数据库正常；失败/阻塞任务 ${dashboard.health.failedTaskCount} 个。`} /><Row gutter={[16,16]} style={{ marginTop: 16 }}><Col span={6}><Card><Statistic title="用户" value={dashboard.users.total} suffix={`活跃 ${dashboard.users.active}`} /></Card></Col><Col span={6}><Card><Statistic title="课程/考试" value={`${dashboard.resources.courses}/${dashboard.resources.exams}`} /></Card></Col><Col span={6}><Card><Statistic title="任务" value={dashboard.tasks.total} suffix={`失败 ${dashboard.tasks.failed}`} /></Card></Col><Col span={6}><Card><Statistic title="AI 调用" value={ai.calls} suffix={`失败率 ${ai.failedRate === null ? '—' : (ai.failedRate*100).toFixed(1)+'%'}`} /></Card></Col></Row><Card title="AI 资源使用" style={{ marginTop: 16 }}><Space size="large"><Statistic title="输入 tokens" value={ai.inputTokens} /><Statistic title="输出 tokens" value={ai.outputTokens} /><Statistic title="平均延迟(ms)" value={ai.averageLatencyMs ?? '—'} /><Statistic title="估算成本" value={ai.estimatedCost ?? '未配置完整价格'} suffix={ai.estimatedCost === null ? undefined : ai.currency ?? undefined} /></Space><Table rowKey={row => `${row.provider}-${row.model}`} pagination={false} dataSource={ai.byModel} columns={[{title:'Provider',dataIndex:'provider'},{title:'模型',dataIndex:'model'},{title:'调用',dataIndex:'calls'},{title:'输入',dataIndex:'inputTokens'},{title:'输出',dataIndex:'outputTokens'},{title:'失败率',dataIndex:'failedRate',render:(v:number|null)=>v===null?'—':`${(v*100).toFixed(1)}%`},{title:'估算成本',dataIndex:'estimatedCost',render:(v:number|null)=>v===null?'价格未覆盖':v.toFixed(6)}]} /></Card></>;
  const userView = <><Button type="primary" onClick={() => setUserOpen(true)} style={{ marginBottom: 12 }}>创建用户</Button><Table rowKey="id" dataSource={users} columns={[{title:'用户名',dataIndex:'username'},{title:'邮箱',dataIndex:'email'},{title:'角色',dataIndex:'role',render:(v:string)=><Tag>{v}</Tag>},{title:'状态',dataIndex:'isActive',render:(v:boolean)=><Tag color={v?'green':'red'}>{v?'启用':'禁用'}</Tag>},{title:'操作',render:(_,row:User)=><Space><Popconfirm title={row.isActive?'确认禁用？现有登录会立即失效。':'确认恢复？'} onConfirm={()=>change(row,{isActive:!row.isActive})}><Button size="small">{row.isActive?'禁用':'恢复'}</Button></Popconfirm><Popconfirm title="使该用户现有登录全部失效？" onConfirm={()=>change(row,{resetLoginState:true})}><Button size="small">重置登录状态</Button></Popconfirm></Space>}]} /></>;
  const costView = <><Alert type="info" showIcon message="成本均为 estimated cost，不是财务账单；未覆盖价格的调用不估算。"/><Button onClick={()=>setCostOpen(true)} style={{margin:'12px 0'}}>新增价格版本</Button><Table rowKey="id" dataSource={costs} columns={[{title:'Provider',dataIndex:'provider'},{title:'模型',dataIndex:'model'},{title:'输入/百万',dataIndex:'inputCostPerMillion'},{title:'输出/百万',dataIndex:'outputCostPerMillion'},{title:'币种',dataIndex:'currency'},{title:'生效时间',dataIndex:'effectiveFrom'}]} /></>;
  return <div><Title level={3}>管理员控制台</Title><Text type="secondary">管理员默认看汇总和元数据，不读取学生具体答案。</Text><Tabs items={[{key:'overview',label:'系统概览',children:overview},{key:'users',label:'用户管理',children:userView},{key:'cost',label:'AI 成本配置',children:costView},{key:'audit',label:'审计日志',children:<Table rowKey="id" dataSource={audit} columns={[{title:'时间',dataIndex:'createdAt'},{title:'动作',dataIndex:'action'},{title:'资源',render:(_,r)=>`${r.resourceType}:${r.resourceId??'-'}`},{title:'request_id',dataIndex:'requestId'}]} />}]} />
    <Modal title="创建用户" open={userOpen} onCancel={()=>setUserOpen(false)} onOk={()=>userForm.submit()}><Form form={userForm} layout="vertical" onFinish={createUser}><Form.Item name="username" label="用户名" rules={[{required:true,min:2}]}><Input/></Form.Item><Form.Item name="email" label="邮箱" rules={[{required:true,type:'email'}]}><Input/></Form.Item><Form.Item name="password" label="初始密码" rules={[{required:true,min:8}]}><Input.Password/></Form.Item><Form.Item name="role" label="角色" rules={[{required:true}]}><Select options={['teacher','student','admin'].map(value=>({value,label:value}))}/></Form.Item></Form></Modal>
    <Modal title="新增 AI 价格版本" open={costOpen} onCancel={()=>setCostOpen(false)} onOk={()=>costForm.submit()}><Form form={costForm} layout="vertical" onFinish={createCost}><Form.Item name="provider" label="Provider" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="model" label="模型" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="inputCostPerMillion" label="输入成本/百万 tokens" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="outputCostPerMillion" label="输出成本/百万 tokens" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="effectiveFrom" label="生效时间" rules={[{required:true}]}><Input type="datetime-local"/></Form.Item></Form></Modal>
  </div>; };
export default AdminConsole;
