import React, { useEffect, useState } from 'react'; import { Alert, Button, Card, Form, Input, InputNumber, Modal, Space, Table, Tag, Typography, message } from 'antd'; import { useSearchParams } from 'react-router-dom';
import type { GradeReview } from '@exam-maker/shared'; import { createGradeReview, listMyGradeReviews } from '../services/gradeReview'; const { Title, Text } = Typography; const { TextArea } = Input;
function errorText(error: unknown) { return (error as { response?: { data?: { error?: string } } })?.response?.data?.error ?? '操作失败'; }
const StudentGradeReviews: React.FC = () => { const [params] = useSearchParams(); const [form] = Form.useForm(); const [rows, setRows] = useState<GradeReview[]>([]); const [open, setOpen] = useState(Boolean(params.get('attemptId'))); const [saving, setSaving] = useState(false);
  const load = () => listMyGradeReviews().then(setRows).catch(error => message.error(errorText(error))); useEffect(() => { load(); if (params.get('attemptId')) form.setFieldValue('attemptId', Number(params.get('attemptId'))); }, []);
  const submit = async (values: { attemptId: number; answerId?: number; reason: string; evidence?: string }) => { setSaving(true); try { await createGradeReview(values); message.success('复核申请已提交'); setOpen(false); form.resetFields(); await load(); } catch (error) { message.error(errorText(error)); } finally { setSaving(false); } };
  return <div><Space style={{ width: '100%', justifyContent: 'space-between' }}><div><Title level={3}>成绩复核</Title><Text type="secondary">申请只会创建待处理记录，不会直接改变成绩。</Text></div><Button type="primary" onClick={() => setOpen(true)}>申请复核</Button></Space>
    <Alert style={{ margin: '16px 0' }} type="info" showIcon message="仅可在教师为该考试设置的复核时间窗内申请；同一成绩项只能有一个待处理申请。" />
    <Card><Table rowKey="id" dataSource={rows} columns={[{ title: '考试', dataIndex: 'examTitle' }, { title: '理由', dataIndex: 'reason', ellipsis: true }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag color={value === 'accepted' ? 'green' : value === 'rejected' ? 'red' : 'orange'}>{value}</Tag> }, { title: '处理说明', dataIndex: 'resolution', render: (value: string | null) => value ?? '待教师处理' }, { title: '申请时间', dataIndex: 'createdAt', render: (value: string) => new Date(value).toLocaleString() }]} /></Card>
    <Modal title="申请成绩复核" open={open} onCancel={() => setOpen(false)} onOk={() => form.submit()} confirmLoading={saving}><Form form={form} layout="vertical" onFinish={submit}><Form.Item name="attemptId" label="作答记录 ID" rules={[{ required: true }]}><InputNumber min={1} style={{ width: '100%' }} /></Form.Item><Form.Item name="answerId" label="具体答案 ID（整卷复核可不填）"><InputNumber min={1} style={{ width: '100%' }} /></Form.Item><Form.Item name="reason" label="复核理由" rules={[{ required: true, min: 5 }]}><TextArea rows={4} /></Form.Item><Form.Item name="evidence" label="补充依据"><TextArea rows={3} /></Form.Item></Form></Modal>
  </div>; };
export default StudentGradeReviews;
