import React, { useEffect, useState } from 'react'; import { Button, Form, Input, InputNumber, Modal, Radio, Space, Table, Tag, Typography, message } from 'antd'; import type { GradeReview } from '@exam-maker/shared'; import { listGradeReviews, resolveGradeReview } from '../services/gradeReview';
const { Title, Text } = Typography; const { TextArea } = Input; function errorText(error: unknown) { return (error as { response?: { data?: { error?: string } } })?.response?.data?.error ?? '操作失败'; }
const TeacherGradeReviews: React.FC = () => { const [rows, setRows] = useState<GradeReview[]>([]); const [selected, setSelected] = useState<GradeReview | null>(null); const [form] = Form.useForm(); const [saving, setSaving] = useState(false); const decision = Form.useWatch('decision', form);
  const load = () => listGradeReviews().then(setRows).catch(error => message.error(errorText(error))); useEffect(() => { load(); }, []);
  const open = (row: GradeReview) => { setSelected(row); form.setFieldsValue({ decision: 'accepted', resolution: '', adjustedScore: undefined }); };
  const submit = async (values: { decision: 'accepted' | 'rejected'; resolution: string; adjustedScore?: number }) => { if (!selected) return; setSaving(true); try { await resolveGradeReview(selected.id, values); message.success('复核处理已保存并写入审计日志'); setSelected(null); await load(); } catch (error) { message.error(errorText(error)); } finally { setSaving(false); } };
  return <div><Title level={3}>成绩复核处理</Title><Text type="secondary">接受且填写调整分数时才会修改对应单题分数，并自动重算整卷成绩。</Text><Table style={{ marginTop: 16 }} rowKey="id" dataSource={rows} columns={[{ title: '考试/学生', render: (_, row: GradeReview) => `${row.examTitle} · ${row.studentName}` }, { title: '理由', dataIndex: 'reason', ellipsis: true }, { title: '当前题分', render: (_, row: GradeReview) => row.answer ? `${row.answer.finalScore ?? '—'}/${row.answer.maxScore}` : '整卷复核' }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag>{value}</Tag> }, { title: '操作', render: (_, row: GradeReview) => row.status === 'pending' ? <Button type="link" onClick={() => open(row)}>处理</Button> : row.resolution }]} />
    <Modal title="处理复核申请" open={Boolean(selected)} onCancel={() => setSelected(null)} onOk={() => form.submit()} confirmLoading={saving}><Form form={form} layout="vertical" onFinish={submit}><Form.Item name="decision" label="决定" rules={[{ required: true }]}><Radio.Group options={[{ value: 'accepted', label: '接受' }, { value: 'rejected', label: '驳回' }]} /></Form.Item>{decision === 'accepted' && selected?.answer && <Form.Item name="adjustedScore" label={`调整后分数（可留空，满分 ${selected.answer.maxScore}）`}><InputNumber min={0} max={selected.answer.maxScore} style={{ width: '100%' }} /></Form.Item>}<Form.Item name="resolution" label="处理说明" rules={[{ required: true, min: 2 }]}><TextArea rows={4} /></Form.Item></Form></Modal>
  </div>; };
export default TeacherGradeReviews;
