import type { NextFunction, Response } from 'express'; import { z } from 'zod'; import { eq } from 'drizzle-orm';
import { createGradeReviewSchema, positiveIdSchema, resolveGradeReviewSchema } from '@exam-maker/shared'; import type { AuthRequest } from '../middleware/auth.js';
import { createGradeReview, listStudentGradeReviews, listTeacherGradeReviews, resolveGradeReview } from '../services/gradeReview.js';
import { db, schema } from '../db/index.js'; import { AppError } from '../middleware/errorHandler.js'; import { canAccessOrganization } from '../middleware/organization.js';
function assertAttemptOrganization(req: AuthRequest, attemptId: number) { const row = db.select({ organizationId: schema.exams.organizationId }).from(schema.attempts).innerJoin(schema.exams, eq(schema.attempts.examId, schema.exams.id)).where(eq(schema.attempts.id, attemptId)).get(); if (!row) throw new AppError(404, '作答记录不存在'); if (!canAccessOrganization(req, row.organizationId)) throw new AppError(403, '无权访问该组织的成绩复核'); }
function assertReviewOrganization(req: AuthRequest, reviewId: number) { const row = db.select({ organizationId: schema.exams.organizationId }).from(schema.gradeReviews).innerJoin(schema.exams, eq(schema.gradeReviews.examId, schema.exams.id)).where(eq(schema.gradeReviews.id, reviewId)).get(); if (!row) throw new AppError(404, '复核申请不存在'); if (!canAccessOrganization(req, row.organizationId)) throw new AppError(403, '无权访问该组织的成绩复核'); }
export function create(req: AuthRequest, res: Response, next: NextFunction) { try { const input = createGradeReviewSchema.parse(req.body); assertAttemptOrganization(req, input.attemptId); res.status(201).json({ success: true, data: createGradeReview(req.userId!, input) }); } catch (error) { next(error); } }
export function mine(req: AuthRequest, res: Response, next: NextFunction) { try { res.json({ success: true, data: listStudentGradeReviews(req.userId!, req.organizationId) }); } catch (error) { next(error); } }
export function teacherList(req: AuthRequest, res: Response, next: NextFunction) { try { const query = z.object({ examId: z.coerce.number().int().positive().optional() }).parse(req.query); const organizationId = req.userRole !== 'admin' || req.organizationExplicit ? req.organizationId : undefined; res.json({ success: true, data: listTeacherGradeReviews(req.userId!, req.userRole as 'teacher' | 'admin', query.examId, organizationId) }); } catch (error) { next(error); } }
export function resolve(req: AuthRequest, res: Response, next: NextFunction) { try { const id = positiveIdSchema.parse(req.params.id); assertReviewOrganization(req, id); res.json({ success: true, data: resolveGradeReview(req.userId!, req.userRole as 'teacher' | 'admin', id, resolveGradeReviewSchema.parse(req.body)) }); } catch (error) { next(error); } }
