import assert from 'node:assert/strict'; import test from 'node:test'; import type { AddressInfo } from 'node:net'; import express from 'express'; import { eq } from 'drizzle-orm';
import { db, initDb, schema } from '../src/db/index.js'; import { runMigrations } from '../src/db/migrate.js'; import { authMiddleware, generateToken } from '../src/middleware/auth.js'; import { errorHandler } from '../src/middleware/errorHandler.js'; import routes from '../src/routes/gradeReview.js'; import { buildPaperSnapshot } from '../src/services/attemptSnapshot.js';
test('grade review enforces time/ownership, changes scores only by teacher decision and writes audit logs', async () => {
  await initDb({ filePath: null }); runMigrations(); db.insert(schema.users).values([{ id: 1, username: 'teacher', email: 'gr-t@test', passwordHash: 'x', role: 'teacher' }, { id: 2, username: 'student', email: 'gr-s@test', passwordHash: 'x', role: 'student' }, { id: 3, username: 'other', email: 'gr-o@test', passwordHash: 'x', role: 'teacher' }]).run();
  db.insert(schema.courses).values({ id: 1, ownerUserId: 1, name: '物理', status: 'active' }).run(); db.insert(schema.questions).values({ id: 1, createdBy: 1, courseId: 1, type: 'single_choice', stem: '题目', answerKey: JSON.stringify({ option: 'A' }), defaultScore: 5 }).run(); db.insert(schema.papers).values({ id: 1, createdBy: 1, courseId: 1, title: '物理卷', course: '物理', totalScore: 5 }).run(); db.insert(schema.paperQuestions).values({ id: 1, paperId: 1, questionId: 1, orderNo: 1, score: 5 }).run();
  db.insert(schema.exams).values({ id: 1, paperId: 1, createdBy: 1, title: '物理考试', status: 'closed', gradeReviewEnabled: true, gradeReviewDeadline: '2099-01-01T00:00:00Z' }).run(); db.insert(schema.examAssignments).values({ id: 1, examId: 1, studentId: 2 }).run(); const snapshot = buildPaperSnapshot(1); db.insert(schema.attempts).values({ id: 1, examId: 1, assignmentId: 1, studentId: 2, status: 'graded', paperSnapshot: JSON.stringify(snapshot), objectiveScore: 2, totalScore: 2 }).run(); db.insert(schema.answers).values({ id: 1, attemptId: 1, paperQuestionId: 1, content: JSON.stringify('B'), autoScore: 2, finalScore: 2, gradingStatus: 'auto_graded' }).run();
  const app = express(); app.use(express.json()); app.use(authMiddleware); app.use('/api/grade-reviews', routes); app.use(errorHandler); const server = await new Promise<ReturnType<typeof app.listen>>(resolve => { const listening = app.listen(0, '127.0.0.1', () => resolve(listening)); }); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api/grade-reviews`;
  const call = async (path: string, userId: number, role: 'teacher' | 'student', method = 'GET', body?: unknown) => { const response = await fetch(`${base}${path}`, { method, headers: { Authorization: `Bearer ${generateToken(userId, role)}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: response.status, body: await response.json() as { data?: any } }; };
  try { const created = await call('', 2, 'student', 'POST', { attemptId: 1, answerId: 1, reason: '自动判分结果与作答证据不一致', evidence: '请复核选项映射' }); assert.equal(created.status, 201); assert.equal(db.select().from(schema.answers).where(eq(schema.answers.id, 1)).get()?.finalScore, 2, 'request cannot modify grade'); assert.equal((await call('', 3, 'teacher')).body.data.length, 0); assert.equal((await call(`/${created.body.data.id}/resolve`, 3, 'teacher', 'PATCH', { decision: 'accepted', resolution: '同意', adjustedScore: 4 })).status, 403);
    const resolved = await call(`/${created.body.data.id}/resolve`, 1, 'teacher', 'PATCH', { decision: 'accepted', resolution: '核对后调整分数', adjustedScore: 4 }); assert.equal(resolved.status, 200); assert.equal(resolved.body.data.status, 'accepted'); assert.equal(db.select().from(schema.answers).where(eq(schema.answers.id, 1)).get()?.finalScore, 4); assert.equal(db.select().from(schema.attempts).where(eq(schema.attempts.id, 1)).get()?.totalScore, 4); assert.equal(db.select().from(schema.gradeAuditLogs).all().length, 2); assert.equal((await call(`/${created.body.data.id}/resolve`, 1, 'teacher', 'PATCH', { decision: 'rejected', resolution: '重复' })).status, 409);
  } finally { await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve())); }
});
